INSERT INTO COUNTRYS(name,id_visa)
VALUES ('Australia VISA',1);
INSERT INTO COUNTRYS(name,id_visa)
VALUES ('Belgium VISA',2);
INSERT INTO COUNTRYS(name,id_visa)
VALUES ('Canada VISA',3);
INSERT INTO COUNTRYS(name,id_visa)
VALUES ('China VISA',4);
INSERT INTO COUNTRYS(name,id_visa)
VALUES ('Denmark VISA',5);
INSERT INTO COUNTRYS(name,id_visa)
VALUES ('England VISA',6);
INSERT INTO COUNTRYS(name,id_visa)
VALUES ('Estonia VISA',7);
INSERT INTO COUNTRYS(name,id_visa)
VALUES ('Finland VISA',8);
INSERT INTO COUNTRYS(name,id_visa)
VALUES ('Greece VISA',9);
INSERT INTO COUNTRYS(name,id_visa)
VALUES ('Iceland VISA',10);
INSERT INTO COUNTRYS(name,id_visa)
VALUES ('India VISA',11);
INSERT INTO COUNTRYS(name,id_visa)
VALUES ('Japan VISA',12);
INSERT INTO COUNTRYS(name,id_visa)
VALUES ('Latvia VISA',13);
INSERT INTO COUNTRYS(name,id_visa)
VALUES ('Luxembourg VISA',14);
INSERT INTO COUNTRYS(name,id_visa)
VALUES ('Malta VISA',15);
INSERT INTO COUNTRYS(name,id_visa)
VALUES ('Mexica VISA',16);
INSERT INTO COUNTRYS(name,id_visa)
VALUES ('Netherlands VISA',17);
INSERT INTO COUNTRYS(name,id_visa)
VALUES ('New Zealand VISA',18);
INSERT INTO COUNTRYS(name,id_visa)
VALUES ('North Korea VISA',19);
INSERT INTO COUNTRYS(name,id_visa)
VALUES ('Norway VISA',20);
INSERT INTO COUNTRYS(name,id_visa)
VALUES ('Singaupore VISA',21);
INSERT INTO COUNTRYS(name,id_visa)
VALUES ('Sweden VISA',22);
INSERT INTO COUNTRYS(name,id_visa)
VALUES ('Switzerland VISA',23);
INSERT INTO COUNTRYS(name,id_visa)
VALUES ('UAE VISA',24);
INSERT INTO COUNTRYS(name,id_visa)
VALUES ('USA VISA',25);