INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Aquamarine Mansion Resort','The city of Rosemore was built among the towering trees of a huge forest and is truly a true modern sight. Its charm is matched by the backdrop of mighty mountains which have helped shape the city to what it is today.',27,767,4);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Historic Vale Resort & Spa','The riches these mountains brought were of great importance',but they were also influential when it came to architectural designs as the vast majority of buildings have been built in the shape of those same mountains.,27,856);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Lunar Canyon Motel','It's this multicultural identity that has truly left its mark. Hundreds of food carts',bars and sandwich bars offer a plethora of culinary choices and those who feel hungry for something else can enjoy an amusement park,theaters,nature or one of the many other recreational venues.);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Regal Phoenix Hotel','The skyline is crowded with impressive skyscrapers and they have aspects which represent their past',present and future. Education is superb in Rosemore and it has attracted a lot of attention. New cultures have left their mark not just on the city's development,but also upon the city's identity. What historically was a city of plain,ordinary people has grown into a multicultural hub and it's this that unites the 11 million people to this day.);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Double Crown Resort','The city of Sunhold was built at the center of a relatively small island and is truly a modest display of wonder. Its allure is matched by the backdrop of clear blue skies which have helped shape the city to what it is today.',1,736,34);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Winter Pass Hotel','The climate these skies brought were of great importance',but they were also influential when it came to architectural designs as the vast majority of buildings were designed to take full advantage of the climate,as more daring elements can be created when you don't have to worry about strong winds.,48);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Nebula Hotel','It's this multicultural identity that has truly left its mark. Hundreds of sandwich bars',diners and ethnic restaurants offer a plethora of culinary choices and those who feel hungry for something else can enjoy adventure sports,musical activities,an amusement park or one of the many other recreational venues.);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Sapphire Resort','The skyline is packed with various skyscrapers and they have aspects which represent their past',present and future. Culture is rising in Sunhold and it has attracted a lot of attention. New cultures have left their mark not just on the city's cuisine,but also upon the city's identity. What historically was a city of predictability has grown into an amalgamation of differences and it's this that unites the 10 million people to this day.,14);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Vertex Hotel & Spa','The city of Southport was built along the banks of modest rivers and is truly an extraordinary trade center. Its beauty is matched by the backdrop of a gentle mountain which have helped shape the city to what it is today.',45,240,29);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Abundance Motel','The climate these mountains brought were of great importance',but they were also influential when it came to architectural designs as the vast majority of buildings mimic the broad slopes and steep peeks of the mountains.,8,508);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Mellow Covert Hotel','It's this multicultural identity that has truly left its mark. Hundreds of sandwich bars',take-outs and clubs offer a plethora of culinary choices and those who feel hungry for something else can enjoy clubs,sport activities,water sports or one of the many other recreational venues.);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Sunrise Ridge Hotel','The skyline is crowded with elaborate skyscrapers and their history seemed to shine more now than ever. Education is superb in Southport and it has attracted a lot of attention. Many different cultures have left their mark not just on the architecture',but also upon the city's identity. What historically was a city of predictability has grown into a new culture of variety and it's this that unites the 5 million people to this day.,27,73);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Obsidian Star Hotel','The city of Earthwall was built at the base of a potentially active volcano and is truly a classic display of wonder. Its uniqueness is matched by the backdrop of pristine skies which have helped shape the city to what it is today.',3,219,8);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Elder Orb Resort','The climate these skies brought were of great importance',but they were also influential when it came to architectural designs as the vast majority of buildings have been built to great heights,as if to try and reach the blue skies above them.,1);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Atlantic Heirloom Hotel & Spa','It's this multicultural identity that has truly left its mark. Hundreds of bistros',cafés and sandwich bars offer a plethora of culinary choices and those who feel hungry for something else can enjoy water sports,an amusement park,clubs or one of the many other recreational venues.);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Primal Manor Resort','The skyline is spreading with elaborate skyscrapers and they each represent the many different aspects of the city. Daily life isn't too stressful in Earthwall and it has attracted a lot of attention. New cultures have left their mark not just on education',but also upon the city's identity. What historically was a city of little diversity has grown into an amalgamation of differences and it's this that unites the 4 million people to this day.,1,669);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Curiosity Resort','The city of Freyport was built atop emerald hills of grass and is truly an extraordinary curiosity. Its uniqueness is matched by the backdrop of gentle hills which have helped shape the city to what it is today.',18,195,27);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Orbit Resort','The resources these hills brought were of great importance',but they were also influential when it came to architectural designs as the vast majority of buildings have been built in shapes and with elements of the hills around them.,25,539);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Panorama Resort','It's this multicultural identity that has truly left its mark. Hundreds of gastropubs',bars and bakeries offer a plethora of culinary choices and those who feel hungry for something else can enjoy musea,theaters,art galleries or one of the many other recreational venues.);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Amber Motel','The skyline is packed with unique skyscrapers and their history seemed to shine more now than ever. Employment is tremendous in Freyport and it has attracted a lot of attention. Various cultures have left their mark not just on the city's development',but also upon the city's identity. What historically was a city of few differences has grown into a fusion of everything and it's this that unites the 7 million people to this day.,16,512);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Riverside Legacy Hotel & Spa','The city of Bellburn was built atop robust hills and is truly a technological urban phenomenon. Its appearance is matched by the backdrop of majestic forests which have helped shape the city to what it is today.',49,822,14);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Lunar Baron Motel','The riches these forests brought were of great importance',but they were also influential when it came to architectural designs as the vast majority of buildings have been built alongside the trees and often incorporate many different forest elements.,15,842);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Soft Fjord Hotel','It's this multicultural identity that has truly left its mark. Hundreds of food carts',sandwich bars and bakeries offer a plethora of culinary choices and those who feel hungry for something else can enjoy dance,one of the many parks,musical activities or one of the many other recreational venues.);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Snowy Rainbow Motel','The skyline is riddled with giant skyscrapers and a new one seems to pop up every other week. Recreation is impeccable in Bellburn and it has attracted a lot of attention. A few new cultures have left their mark not just on the city's cuisine',but also upon the city's identity. What historically was a city of no variation has grown into a large melting pot and it's this that unites the 6 million people to this day.,43,773);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Silver Summit Resort & Spa','The city of Ironford was built on the banks of a man-made harbor and is truly a modest display of wonder. Its charm is matched by the backdrop of a smoldering volcano which have helped shape the city to what it is today.',27,583,7);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Elder Dream Hotel','The materials these volcanoes brought were of great importance',but they were also influential when it came to architectural designs as the vast majority of buildings incorporate shapes and colors of both the volcano and of lava.,13,528);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Epitome Hotel','It's this multicultural identity that has truly left its mark. Hundreds of bakeries',restaurants and diners offer a plethora of culinary choices and those who feel hungry for something else can enjoy city exploring,aerobics,arcades or one of the many other recreational venues.);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Harborview Resort & Spa','The skyline is packed with elegant skyscrapers and each was more impressive than the next. Employment is tremendous in Ironford and it has attracted a lot of attention. New cultures have left their mark not just on the architecture',but also upon the city's identity. What historically was a city of little diversity has grown into a large melting pot and it's this that unites the 3 million people to this day.,4,240);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Ornate Resort & Spa','The city of Embercrest was built atop gentle hills and is truly a true modern urban phenomenon. Its allure is matched by the backdrop of an abundance of hills which have helped shape the city to what it is today.',23,856,15);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Stardust Resort','The trade resources these hills brought were of great importance',but they were also influential when it came to architectural designs as the vast majority of buildings follow the flowing round shapes of those very same hills and continue the overall aesthetics.,30,383);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Obsidian Plaza Hotel','It's this multicultural identity that has truly left its mark. Hundreds of bars',clubs and diners offer a plethora of culinary choices and those who feel hungry for something else can enjoy tours,one of the many parks,nature or one of the many other recreational venues.);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Regal Horizon Hotel','The skyline is crowded with elegant skyscrapers and their history seemed to shine more now than ever. Culture is rising in Embercrest and it has attracted a lot of attention. Countless cultures have left their mark not just on international relations',but also upon the city's identity. What historically was a city of little contrast has grown into a new culture of variety and it's this that unites the 7 million people to this day.,15,402);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Serene Treasure Resort','The city of Westborough was built amidst the windy fields of gentle grasslands and is truly a fully modernized phenomenon. Its uniqueness is matched by the backdrop of cascading waterfalls which have helped shape the city to what it is today.',12,473,24);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Ebony Crow Hotel','The climate these waterfalls brought were of great importance',but they were also influential when it came to architectural designs as the vast majority of buildings not only use water from those waterfalls,they often incorporate some form of falling water as part of their architecture.,46);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Olive Plaza Resort & Spa','It's this multicultural identity that has truly left its mark. Hundreds of sandwich bars',clubs and theme restaurants offer a plethora of culinary choices and those who feel hungry for something else can enjoy concerts,art galleries,city exploring or one of the many other recreational venues.);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Primal Expanse Hotel','The skyline is sprinkled with various skyscrapers and they clearly show what they represent to the city itself. Parks and gardens are flourishing in Westborough and it has attracted a lot of attention. Many new cultures have left their mark not just on the city's development',but also upon the city's identity. What historically was a city of plain,ordinary people has grown into a new culture of variety and it's this that unites the 7 million people to this day.,21);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Fantasy Hotel','The city of Freyport was built in a seemingly endless desert and is truly a technological display of wonder. Its charm is matched by the backdrop of everclear skies which have helped shape the city to what it is today.',13,736,16);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Fairyland Hotel','The climate these skies brought were of great importance',but they were also influential when it came to architectural designs as the vast majority of buildings were designed to take full advantage of the climate,as more daring elements can be created when you don't have to worry about strong winds.,3);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Paradise Hotel','It's this multicultural identity that has truly left its mark. Hundreds of cafés',take-outs and diners offer a plethora of culinary choices and those who feel hungry for something else can enjoy aerobics,musical activities,photography or one of the many other recreational venues.);
INSERT INTO HOTELS (name,discription,numberRooms,priceNight,id_city)
VALUES('Baroque Hotel','The skyline is packed with unique skyscrapers and a lot of them seem to have evolved throughout the ages. Daily life isn't too stressful in Freyport and it has attracted a lot of attention. Many different cultures have left their mark not just on the city's people',but also upon the city's identity. What historically was a city of no variation has grown into a new culture of variety and it's this that unites the 6 million people to this day.,2,723);
