INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Karl','Lermontov', 'lermontovkarl56@gmail.com','66aLNapG',17,TRUE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Genrih','Obreskov', 'obreskovgenrih78@gmail.com','U_ZE!85V',9,TRUE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Fabian','Naryshkin', 'naryshkinfabian18@gmail.com','ZtFqa9BO',19,TRUE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Karl','Skuratov', 'skuratovkarl64@gmail.com','lq_^Ibr4',3,TRUE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Petroniy','Raevskiy', 'raevskiypetroniy11@gmail.com','Yj0kuIz*',19,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Tiberiy','Goncharov', 'goncharovtiberiy80@gmail.com','h6*dInXq',23,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Gektor','Bestuzhev', 'bestuzhevgektor92@gmail.com','6#fE03Lo',21,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Adrian','Bestuzhev', 'bestuzhevadrian72@gmail.com','yj^HOYfJ',21,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Franczisk','Rostopchin', 'rostopchinfranczisk66@gmail.com','IkoruZeT',13,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Zigmund','Nashhokin', 'nashhokinzigmund99@gmail.com','Skumbo^D',23,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Gerakl','Vyazemskiy', 'vyazemskiygerakl36@gmail.com','avtkVfKv',3,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Gannibal','Hovanskiy', 'hovanskiygannibal54@gmail.com','inb*f0Ao',2,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Karl','Obolyaninov', 'obolyaninovkarl21@gmail.com','AZUtF_P4',9,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Klavdiy','Rumyanczev', 'rumyanczevklavdiy15@gmail.com','QhdK*jOJ',1,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Roland','Shheglovitov', 'shheglovitovroland86@gmail.com','k06qxG8m',24,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Fabian','Sheremetev', 'sheremetevfabian14@gmail.com','6rL#M9pF',12,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Narcziss','Razumovskiy', 'razumovskiynarcziss33@gmail.com','AqWu^eM7',19,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Nestor','Volkonskiy', 'volkonskiynestor74@gmail.com','1IW5*6rG',15,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Adrian','Meshherskiy', 'meshherskiyadrian38@gmail.com','Na@WP_KR',16,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Spartak','Shahovskoy', 'shahovskoyspartak98@gmail.com','OZlHMLFm',12,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Narcziss','Romodanovskiy', 'romodanovskiynarcziss35@gmail.com','dKiWtugo',12,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Tiberiy','Orlov', 'orlovtiberiy11@gmail.com','Lu5O*@UD',18,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Yuliy','Obolenskiy', 'obolenskiyyuliy100@gmail.com','52o!dJqg',1,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Platon','Oginskiy', 'oginskiyplaton37@gmail.com','Z8Ygf@AV',17,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Franczisk','Mertvago', 'mertvagofranczisk97@gmail.com','3^BN3M8r',12,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Avreliy','Pushhin', 'pushhinavreliy75@gmail.com','4pN1Yao@',24,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Pompey','Orlov', 'orlovpompey61@gmail.com','ylaR^cA4',7,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Zigfrid','Hodkevich', 'hodkevichzigfrid15@gmail.com','ZgbEv2Fw',16,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Gannibal','Razumovskiy', 'razumovskiygannibal25@gmail.com','7OjgpVPl',3,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Roland','Kutuzov', 'kutuzovroland62@gmail.com','c#BftNvh',19,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Avreliy','Vishneveczkiy', 'vishneveczkiyavreliy1@gmail.com','umJ#Jt^M',23,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Yuniy','Adadurov', 'adadurovyuniy64@gmail.com','jDj3116f',24,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Arkadiy','Rahlin', 'rahlinarkadiy42@gmail.com','o2IjKFMZ',1,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Korniliy','Reznik', 'reznikkorniliy58@gmail.com','xfH2v!Sm',24,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Lazar','Shmulevich', 'shmulevichlazar37@gmail.com','eaNYCeql',1,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Paramon','Rabiner', 'rabinerparamon17@gmail.com','sxXB49qd',8,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Martimian','Levin', 'levinmartimian92@gmail.com','5sXevfH2',24,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Mark','Shpigel', 'shpigelmark2@gmail.com','6L23hNn*',23,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Panteleimon','Shpigel', 'shpigelpanteleimon94@gmail.com','nWvGaMvr',16,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Sevastian','Finkelshteyn', 'finkelshteynsevastian7@gmail.com','CagypHWA',8,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Gerasim','Levinson', 'levinsongerasim37@gmail.com','ENnnRzgk',14,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Avksentiy','Perecz', 'pereczavksentiy1@gmail.com','m6HN6wKQ',7,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Filon','Frank', 'frankfilon87@gmail.com','Bk4VydyF',8,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Guriy','Girshman', 'girshmanguriy51@gmail.com','FHnY2wvf',4,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Manuil','Rabiner', 'rabinermanuil16@gmail.com','4xEvO!T2',19,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Kiriak','Goldshmidt', 'goldshmidtkiriak54@gmail.com','HCXnpIq9',2,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Iustin','Meyer', 'meyeriustin92@gmail.com','OLM5yr8S',16,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Artemon','Gleyzer', 'gleyzerartemon64@gmail.com','1nq0Gzr8',4,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Iustin','Shenderovich', 'shenderovichiustin61@gmail.com','ghbUgVTJ',21,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Artemon','Yankelevich', 'yankelevichartemon90@gmail.com','tv2_1bL!',14,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Adam','Ginczburg', 'ginczburgadam88@gmail.com','I2u!6b@F',11,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Savvatiy','Mendel', 'mendelsavvatiy37@gmail.com','om!ek*9i',21,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Kronid','Lure', 'lurekronid24@gmail.com','RiNJiQ42',25,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Adrian','Kramer', 'krameradrian94@gmail.com','swVtrwdn',15,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Modest','Rabiner', 'rabinermodest53@gmail.com','xuax#U#V',16,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Apollinariy','Gleyzer', 'gleyzerapollinariy77@gmail.com','P^j9KbT2',13,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Gavriil','Shnayder', 'shnaydergavriil98@gmail.com','@LUoVvZ7',19,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Veniamin','Averbah', 'averbahveniamin55@gmail.com','fm2MSgFU',4,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Pimen','Vulf', 'vulfpimen20@gmail.com','#^Q0V3ft',8,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Firs','Vasserman', 'vassermanfirs93@gmail.com','*ErNiDR2',1,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Evtihiy','Gershfeld', 'gershfeldevtihiy27@gmail.com','vUzjZaa*',16,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Isaak','Volf', 'volfisaak87@gmail.com','dpZ1ICfZ',1,FALSE);
INSERT INTO USERS(firstName,lastName,email,password,id_country,isAdmin)
VALUES ('Kassian','Ioffe', 'ioffekassian26@gmail.com','D_a_DUUx',14,FALSE);